### ISSUE TITLE
Error 500 on pwabuilder-api-pre.azurewebsites.net when trying to generate MacOS files (and Progressive Web App files too)

### ISSUE THREAD

**Issue by loran750** [pwa-builder/pwabuilder-MacOS#17] opened 2020-06-29 23:45 UTC
When clicking on MacOS, we get on the website this message :
"The manifest is not valid. Review the validation messages above for additional information."
even if the manifest is full correct.
In fact in the console there is a 500 error when POST-ing : 
https://pwabuilder-api-pre.azurewebsites.net/manifests/11084dcd/build?ids=1&href=https://xxxxxxxxxxxxxxxxxxxxxxxxx

and the content of this URL is : "Not Found"

**Comment by JudahGabriel** [comment] 2020-07-02 20:21
Can you send us your URL?

**Comment by loran750** [comment] 2020-07-02 20:58
here is the link : https:// truckalert .fr/   (i've added spaces)
Anyway, no URL is working currently on pwabuilder.com, the Manifest and Service Worker blocks are KO

**Comment by JudahGabriel** [comment] 2020-07-03 16:53
We had an issue with our deployed services, those are fixed now.

I'm able to repro your problem. @lee-leonardo can you have a look at this?

**Comment by JudahGabriel** [comment] 2020-07-07 17:37
@loran750 investigating this further, we think there's a bug in our MacOS platform with handling icons that have dual purpose (e.g. purpose: "any maskable". We are investigating and should have a fix soon.

**Comment by lee-leonardo** [comment] 2020-07-07 23:56
The issue is within the tv4 dependency, it's failing due to a property not being recognized as valid in the schema:

```
{
...
"icons": [{
  ...
  "purpose": "any maskable"
}]
}
```

any and maskable are valid, but the combination as a string is being recognized as not.
Looking at the W3C manifest (to check if valid) and see if we can extend the dependency's comparator.

**Comment by JudahGabriel** [comment] 2020-07-10 20:18
@lee-leonardo yeah, according to [W3C spec](https://w3c.github.io/manifest/#purpose-member), an icon can have many purposes:

> The purpose member is an unordered set of unique space-separated tokens that are ASCII case-insensitive. The allowed values are the icon purposes.

In the front-end code, we just do something like 

```js
const desiredPurpose = 'maskable';
purposes.split(' ').includes(desiredPurpose);
```

**Comment by lee-leonardo** [comment] 2020-07-20 23:23
@loran750 the issue is fixed now, if you are still blocked please try again!

**Comment by JudahGabriel** [comment] 2020-07-20 23:38
I've verified your URL now works correctly when generated the MacOS package. 👍

**Closed by JudahGabriel** 2020-07-20 23:38 UTC
Labels: bug, fixed
